language: generic
dist: trusty
sudo: required

matrix:
  include:

  - language: python3
    env:
    - JOBNAME=UNIT_TESTS

    install:
    - sudo apt-get install -y libsqlcipher-dev
    - pip3 install -r requirements.txt
    - pip3 install dpytest==0.0.20
    - pip3 install discord.py==1.3.4
    - cd cogs
    - cat TextFilter.py
    - cd ..

    script:
    - python3 -m pytest tests