language: generic
dist: xenial
sudo: required

matrix:
  include:

  - language: python
    env:
    - JOBNAME=UNIT_TESTS

    python:
    - "3.8"

    install:
    - python --version
    - sudo apt-get install -y libsqlcipher-dev
    - pip3 install -r requirements.txt
    - pip3 install discord.py==1.3.4

    script:
    - python -m pytest tests
